#!/usr/bin/env bash
# fix-env.sh — מעדכן את 2 הערכים החסרים ב-.env.local
# הרצה: bash fix-env.sh

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

[ -f .env.local ] || { echo "אין .env.local — הרץ init.sh"; exit 1; }

source .env.local 2>/dev/null || true
URL_FROM_ENV="${VITE_SUPABASE_URL:-}"

# חישוב REF אוטומטי מה-URL (xxx.supabase.co → xxx)
DEFAULT_REF=$(echo "$URL_FROM_ENV" | sed -E 's|https?://||; s|\.supabase\.co.*||')

echo "URL נוכחי: $URL_FROM_ENV"
echo "REF משוער מה-URL: $DEFAULT_REF"
echo

printf "? Reference ID [%s]: " "$DEFAULT_REF"
read -r NEW_REF
NEW_REF="${NEW_REF:-$DEFAULT_REF}"

printf "? service_role key (קלט מוסתר, מתחיל ב-sb_secret_ או eyJ): "
read -rs NEW_SERVICE
echo

[ -z "$NEW_SERVICE" ] && { echo "שגיאה: לא הוזן service_role"; exit 1; }
[ -z "$NEW_REF" ] && { echo "שגיאה: לא הוזן REF"; exit 1; }

# עדכון הערכים בקובץ (sed עם backup)
sed -i.bak \
  -e "s|^SUPABASE_SERVICE_ROLE_KEY=.*|SUPABASE_SERVICE_ROLE_KEY=$NEW_SERVICE|" \
  -e "s|^SUPABASE_PROJECT_REF=.*|SUPABASE_PROJECT_REF=$NEW_REF|" \
  .env.local
rm -f .env.local.bak

# גם config.toml
if [ -f supabase/config.toml ]; then
  sed -i.bak "s|^project_id = .*|project_id = \"$NEW_REF\"|" supabase/config.toml
  rm -f supabase/config.toml.bak
fi

# גם cron-bootstrap.sql
mkdir -p supabase/setup
cat > supabase/setup/cron-bootstrap.sql <<EOF
-- Auto-generated by fix-env.sh — אל תקמיט.
alter database postgres set "app.supabase_url" = '$URL_FROM_ENV';
alter database postgres set "app.service_role_key" = '$NEW_SERVICE';
EOF
chmod 600 supabase/setup/cron-bootstrap.sql

echo
echo "✓ .env.local עודכן"
echo "✓ supabase/config.toml עודכן (project_id=$NEW_REF)"
echo "✓ supabase/setup/cron-bootstrap.sql רוענן"
echo
echo "בדיקה מהירה:"
source .env.local
echo "  SERVICE len: ${#SUPABASE_SERVICE_ROLE_KEY}"
echo "  REF: $SUPABASE_PROJECT_REF"
